/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MessageLecturerDTO
    /// </summary>
    [DataContract]
        public partial class MessageLecturerDTO :  IEquatable<MessageLecturerDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageLecturerDTO" /> class.
        /// </summary>
        /// <param name="lecturerId">lecturerId.</param>
        /// <param name="discussionId">discussionId.</param>
        /// <param name="id">id.</param>
        /// <param name="time">time.</param>
        /// <param name="content">content.</param>
        public MessageLecturerDTO(int? lecturerId = default(int?), int? discussionId = default(int?), int? id = default(int?), string time = default(string), string content = default(string))
        {
            this.LecturerId = lecturerId;
            this.DiscussionId = discussionId;
            this.Id = id;
            this.Time = time;
            this.Content = content;
        }
        
        /// <summary>
        /// Gets or Sets LecturerId
        /// </summary>
        [DataMember(Name="LecturerId", EmitDefaultValue=false)]
        public int? LecturerId { get; set; }

        /// <summary>
        /// Gets or Sets DiscussionId
        /// </summary>
        [DataMember(Name="DiscussionId", EmitDefaultValue=false)]
        public int? DiscussionId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Time
        /// </summary>
        [DataMember(Name="Time", EmitDefaultValue=false)]
        public string Time { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name="Content", EmitDefaultValue=false)]
        public string Content { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessageLecturerDTO {\n");
            sb.Append("  LecturerId: ").Append(LecturerId).Append("\n");
            sb.Append("  DiscussionId: ").Append(DiscussionId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MessageLecturerDTO);
        }

        /// <summary>
        /// Returns true if MessageLecturerDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of MessageLecturerDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageLecturerDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LecturerId == input.LecturerId ||
                    (this.LecturerId != null &&
                    this.LecturerId.Equals(input.LecturerId))
                ) && 
                (
                    this.DiscussionId == input.DiscussionId ||
                    (this.DiscussionId != null &&
                    this.DiscussionId.Equals(input.DiscussionId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Time == input.Time ||
                    (this.Time != null &&
                    this.Time.Equals(input.Time))
                ) && 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LecturerId != null)
                    hashCode = hashCode * 59 + this.LecturerId.GetHashCode();
                if (this.DiscussionId != null)
                    hashCode = hashCode * 59 + this.DiscussionId.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Time != null)
                    hashCode = hashCode * 59 + this.Time.GetHashCode();
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
