/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AttendancesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AttendancesApiTests
    {
        private AttendancesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AttendancesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AttendancesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AttendancesApi
            //Assert.IsInstanceOfType(typeof(AttendancesApi), instance, "instance is a AttendancesApi");
        }

        /// <summary>
        /// Test ApiAttendancesGet
        /// </summary>
        [Test]
        public void ApiAttendancesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAttendancesGet();
            //Assert.IsInstanceOf<List<AttendanceDTO>> (response, "response is List<AttendanceDTO>");
        }
        /// <summary>
        /// Test ApiAttendancesIdDelete
        /// </summary>
        [Test]
        public void ApiAttendancesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiAttendancesIdDelete(id);
            //Assert.IsInstanceOf<AttendanceDTO> (response, "response is AttendanceDTO");
        }
        /// <summary>
        /// Test ApiAttendancesIdGet
        /// </summary>
        [Test]
        public void ApiAttendancesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiAttendancesIdGet(id);
            //Assert.IsInstanceOf<AttendanceDTO> (response, "response is AttendanceDTO");
        }
        /// <summary>
        /// Test ApiAttendancesIdPut
        /// </summary>
        [Test]
        public void ApiAttendancesIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //AttendanceDTO body = null;
            //instance.ApiAttendancesIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiAttendancesPost
        /// </summary>
        [Test]
        public void ApiAttendancesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AttendanceDTO body = null;
            //var response = instance.ApiAttendancesPost(body);
            //Assert.IsInstanceOf<AttendanceDTO> (response, "response is AttendanceDTO");
        }
    }

}
