/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LecturersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LecturersApiTests
    {
        private LecturersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LecturersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LecturersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LecturersApi
            //Assert.IsInstanceOfType(typeof(LecturersApi), instance, "instance is a LecturersApi");
        }

        /// <summary>
        /// Test ApiLecturersGet
        /// </summary>
        [Test]
        public void ApiLecturersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            var response = instance.ApiLecturersGet();
            Assert.IsInstanceOf<List<LecturerDTO>>(response, "response is List<LecturerDTO>");
        }
        /// <summary>
        /// Test ApiLecturersIdDelete
        /// </summary>
        [Test]
        public void ApiLecturersIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiLecturersIdDelete(id);
            //Assert.IsInstanceOf<LecturerDTO> (response, "response is LecturerDTO");
        }
        /// <summary>
        /// Test ApiLecturersIdGet
        /// </summary>
        [Test]
        public void ApiLecturersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiLecturersIdGet(id);
            //Assert.IsInstanceOf<LecturerDTO> (response, "response is LecturerDTO");
        }
        /// <summary>
        /// Test ApiLecturersIdPut
        /// </summary>
        [Test]
        public void ApiLecturersIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //LecturerDTO body = null;
            //instance.ApiLecturersIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiLecturersPost
        /// </summary>
        [Test]
        public void ApiLecturersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LecturerDTO body = null;
            //var response = instance.ApiLecturersPost(body);
            //Assert.IsInstanceOf<LecturerDTO> (response, "response is LecturerDTO");
        }
    }

}
