/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RatesApiTests
    {
        private RatesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RatesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RatesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RatesApi
            //Assert.IsInstanceOfType(typeof(RatesApi), instance, "instance is a RatesApi");
        }

        /// <summary>
        /// Test ApiRatesGet
        /// </summary>
        [Test]
        public void ApiRatesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiRatesGet();
            //Assert.IsInstanceOf<List<RateDTO>> (response, "response is List<RateDTO>");
        }
        /// <summary>
        /// Test ApiRatesIdDelete
        /// </summary>
        [Test]
        public void ApiRatesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiRatesIdDelete(id);
            //Assert.IsInstanceOf<RateDTO> (response, "response is RateDTO");
        }
        /// <summary>
        /// Test ApiRatesIdGet
        /// </summary>
        [Test]
        public void ApiRatesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiRatesIdGet(id);
            //Assert.IsInstanceOf<RateDTO> (response, "response is RateDTO");
        }
        /// <summary>
        /// Test ApiRatesIdPut
        /// </summary>
        [Test]
        public void ApiRatesIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //RateDTO body = null;
            //instance.ApiRatesIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiRatesPost
        /// </summary>
        [Test]
        public void ApiRatesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RateDTO body = null;
            //var response = instance.ApiRatesPost(body);
            //Assert.IsInstanceOf<RateDTO> (response, "response is RateDTO");
        }
    }

}
