/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SemestersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SemestersApiTests
    {
        private SemestersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SemestersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SemestersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SemestersApi
            //Assert.IsInstanceOfType(typeof(SemestersApi), instance, "instance is a SemestersApi");
        }

        /// <summary>
        /// Test ApiSemestersGet
        /// </summary>
        [Test]
        public void ApiSemestersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiSemestersGet();
            //Assert.IsInstanceOf<List<SemesterDTO>> (response, "response is List<SemesterDTO>");
        }
        /// <summary>
        /// Test ApiSemestersIdDelete
        /// </summary>
        [Test]
        public void ApiSemestersIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiSemestersIdDelete(id);
            //Assert.IsInstanceOf<SemesterDTO> (response, "response is SemesterDTO");
        }
        /// <summary>
        /// Test ApiSemestersIdGet
        /// </summary>
        [Test]
        public void ApiSemestersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiSemestersIdGet(id);
            //Assert.IsInstanceOf<SemesterDTO> (response, "response is SemesterDTO");
        }
        /// <summary>
        /// Test ApiSemestersIdPut
        /// </summary>
        [Test]
        public void ApiSemestersIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //SemesterDTO body = null;
            //instance.ApiSemestersIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiSemestersPost
        /// </summary>
        [Test]
        public void ApiSemestersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SemesterDTO body = null;
            //var response = instance.ApiSemestersPost(body);
            //Assert.IsInstanceOf<SemesterDTO> (response, "response is SemesterDTO");
        }
    }

}
