/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TestsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TestsApiTests
    {
        private TestsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TestsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TestsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TestsApi
            //Assert.IsInstanceOfType(typeof(TestsApi), instance, "instance is a TestsApi");
        }

        /// <summary>
        /// Test ApiTestsGet
        /// </summary>
        [Test]
        public void ApiTestsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiTestsGet();
            //Assert.IsInstanceOf<List<TestDTO>> (response, "response is List<TestDTO>");
        }
        /// <summary>
        /// Test ApiTestsIdDelete
        /// </summary>
        [Test]
        public void ApiTestsIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiTestsIdDelete(id);
            //Assert.IsInstanceOf<TestDTO> (response, "response is TestDTO");
        }
        /// <summary>
        /// Test ApiTestsIdGet
        /// </summary>
        [Test]
        public void ApiTestsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiTestsIdGet(id);
            //Assert.IsInstanceOf<TestDTO> (response, "response is TestDTO");
        }
        /// <summary>
        /// Test ApiTestsIdPut
        /// </summary>
        [Test]
        public void ApiTestsIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //TestDTO body = null;
            //instance.ApiTestsIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiTestsOfLessionLessionIdGet
        /// </summary>
        [Test]
        public void ApiTestsOfLessionLessionIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? lessionId = null;
            //var response = instance.ApiTestsOfLessionLessionIdGet(lessionId);
            //Assert.IsInstanceOf<List<TestDTO>> (response, "response is List<TestDTO>");
        }
        /// <summary>
        /// Test ApiTestsPost
        /// </summary>
        [Test]
        public void ApiTestsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TestDTO body = null;
            //var response = instance.ApiTestsPost(body);
            //Assert.IsInstanceOf<TestDTO> (response, "response is TestDTO");
        }
    }

}
