/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessageLecturerDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageLecturerDTOTests
    {
        // TODO uncomment below to declare an instance variable for MessageLecturerDTO
        //private MessageLecturerDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageLecturerDTO
            //instance = new MessageLecturerDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageLecturerDTO
        /// </summary>
        [Test]
        public void MessageLecturerDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageLecturerDTO
            //Assert.IsInstanceOfType<MessageLecturerDTO> (instance, "variable 'instance' is a MessageLecturerDTO");
        }


        /// <summary>
        /// Test the property 'LecturerId'
        /// </summary>
        [Test]
        public void LecturerIdTest()
        {
            // TODO unit test for the property 'LecturerId'
        }
        /// <summary>
        /// Test the property 'DiscussionId'
        /// </summary>
        [Test]
        public void DiscussionIdTest()
        {
            // TODO unit test for the property 'DiscussionId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
