/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuestionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuestionDTOTests
    {
        // TODO uncomment below to declare an instance variable for QuestionDTO
        //private QuestionDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuestionDTO
            //instance = new QuestionDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuestionDTO
        /// </summary>
        [Test]
        public void QuestionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuestionDTO
            //Assert.IsInstanceOfType<QuestionDTO> (instance, "variable 'instance' is a QuestionDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Solution'
        /// </summary>
        [Test]
        public void SolutionTest()
        {
            // TODO unit test for the property 'Solution'
        }
        /// <summary>
        /// Test the property 'TestId'
        /// </summary>
        [Test]
        public void TestIdTest()
        {
            // TODO unit test for the property 'TestId'
        }

    }

}
