/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RateDTOTests
    {
        // TODO uncomment below to declare an instance variable for RateDTO
        //private RateDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RateDTO
            //instance = new RateDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RateDTO
        /// </summary>
        [Test]
        public void RateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RateDTO
            //Assert.IsInstanceOfType<RateDTO> (instance, "variable 'instance' is a RateDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'StudentId'
        /// </summary>
        [Test]
        public void StudentIdTest()
        {
            // TODO unit test for the property 'StudentId'
        }
        /// <summary>
        /// Test the property 'LessionId'
        /// </summary>
        [Test]
        public void LessionIdTest()
        {
            // TODO unit test for the property 'LessionId'
        }

    }

}
