/* 
 * Smart Class API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmissionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionDTOTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionDTO
        //private SubmissionDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionDTO
            //instance = new SubmissionDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionDTO
        /// </summary>
        [Test]
        public void SubmissionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionDTO
            //Assert.IsInstanceOfType<SubmissionDTO> (instance, "variable 'instance' is a SubmissionDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Point'
        /// </summary>
        [Test]
        public void PointTest()
        {
            // TODO unit test for the property 'Point'
        }
        /// <summary>
        /// Test the property 'TestId'
        /// </summary>
        [Test]
        public void TestIdTest()
        {
            // TODO unit test for the property 'TestId'
        }
        /// <summary>
        /// Test the property 'StudentId'
        /// </summary>
        [Test]
        public void StudentIdTest()
        {
            // TODO unit test for the property 'StudentId'
        }

    }

}
